### ISSUE TITLE
Help -? functionality

### ISSUE THREAD

**Issue by ielizaga** [ielizaga/gpcheckintegrity#9]
Currently a command-line help (-?) doesn't exist to let the user know about the usage of this tool. This issue tracks the development of this feature.

**Comment by Zerpet** [comment]
`OptionsParser` from `gplib` is a bit particular. It expects a text file in `../docs/cli_help/<command>_help`. It assumes that all the commands are executed from `bin/`; which is not true in this case since we are (or want to be) independent from GPPy libraries.

As workaround, I can implement this as a callback to the help option. I would like to refactor this "thing" at some point.

**Comment by ielizaga** [comment]
Merged in #13.
